#+title: Daily work log for srivalya

* Month of May
** [2016-05-16 Mon]
   + What is the task I was assigned today?
     + To create git repository, clone,push,pull and fork it.
     + used git commit,add,reset,checkout,status and reset.
   + What did I get done against each task?
** [2016-05-17 Tue]
   + what is the task I was assigned today?
     + To create html file using emacs
     + exporting the html file to browser
     + Data models was taught and a task of identifying the entities, the
       contraints etc was assigned.
 
   + What did I get done against each task?
     ++ Learnt how to 
     +++ Export org file as html to the browser
     +++ How to make the a word as link
** [2016-05-18 wed]
    + What is the task I was assigned today?
      + To build the object model
    + What did I get from completing the task?
      +Completed the user,email and role classes and their testcases.
** [2016-05-19 thu]
    + What is the task I was assigned today?
      + To build the object model
    + What did I get from completing the task?
      +Completed the session class and few extra operations and their testcases.
** [2016-05-20 fri]
   + What is the task I was assigned today?
     + To build the object model and testcases 
   + What did I get from completing the task?
     + Moved the add_user,delete_user,update_role to a new class called system.
       This class has list of users and sessions.
       what I learnt today is that only the methods which can modify the
       attributes should belong to that class.
  
** Weekly  Summary
   + What are the insights gained?
     I have learnt how to build an Object Model and link the database to that model.

   + What is my footprint in the realization of the project?

      
** [2016-05-23 Mon]
   + What is the task I was assigned today?
     An intro to how database works was given. We were asked to build the persistence layer for the object model.
   + What did I get done against each task?
     Downloaded the boiler-plate code and started working on the methods and the test-cases of the persistence layer.
     
** [2016-05-24 Tue]
   + what is the task I was assigned today?
     + To complete the ORM 
   + What did I get done against each task?
     + Completed modifying the methods and wrote a few the testcases for ORM. 
     
** [2016-05-25 wed]
    + What is the task I was assigned today?
      + To complete the ORM 
    + What did I get from completing the task?
      + Finished writing all the testcases for the ORM 
      
** [2016-05-26 thu]
    + What is the task I was assigned today?
      + To build the REST API for the given web application, by referring to the functionality of the ORM.
    + What did I get from completing the task?
      + A boiler-plate code was given and added the required functionality.
      
** [2016-05-27 fri]
   + What is the task I was assigned today?
      + Update the REST API and implemented all the System class methods in the API.
   + What did I get from completing the task?

** [2016-05-30 Mon]
   + Task assigned today: To start working on the front end.
   +  What did I get done against each task? Implemented login and logout in the rest API.
** [2016-05-31 Tue]
   + Task assigned today: To write the test cases for login and logout restAPI. Started working with view list of users.   
   + what did I get done against each task? Got the test cases working.  
* Month of June

** [2016-06-1 Wed]
   + Task assigned today: Fixed the error in viewing the of users and started working with add, delete and edit user. 
   + What did I get done against each task? Done with add, delete and edit user.

** [2016-06-2 Thu]
   + Task assigned today: We had to do manual deployment and automatic deployment of our web application.
   + What did I get done against each task? We deployed the web application deployed on an external host, using both a manual deployment and an ADS.
** [2016-06-3 Fri]
   + Task assigned today? To give a small presentation on the completed web application made during the boot camp,and present the documentation.
   + What did I get done against the task? Presented the documentation on the completed web application, and demonstrated the working of the application, along with displaying the running test cases.

** [2016-06-6 Mon]
   + Task assigned today? To understand the PDF forwarded by mentor about big data, why is it necessary and importance to have security policies for huge data. 

** [2016-06-7 Tue]
   + Task assigned today? Spoke to my mentor, he explained me a senario where certain resources which agents can access, there are restriction policies as how they can utilize the resouces for different types agents so that the data is secured.   
      He asked me to write a specification language for this senario.
** [2016-06-8 Wed]
   + Task assigned today? Still working on the specification language as he asked me to modify the previous one I had sent.
** [2016-06-09 Thu]
   + Task assigned today? Still modifying the specification language.
** [2016-06-9 Fri]
   + Task assigned today? Couldn't communicate with my mentor as he was busy with some other work today. I didnt have much to do today.
   
* Month of July
